CREATE TABLE "GCG_6495_MPU9_LA_WINTER" (
 "UpdateDate" DATE,
 "Grade" CHAR(4),
 "Size" CHAR(16),
 "ActivatorPerToAdd" NUMERIC(5,2),
 "ActivatorType" CHAR(30),
 "CatalystPerToAdd" NUMERIC(5,2),
 "PourTemp" NUMERIC(5,0),
 "PourWeight" NUMERIC(5,0),
 "DyeType" CHAR(30),
 "DyePerToAdd" NUMERIC(5,2),
 "AdditionalType" CHAR(30),
 "AdditionalPerToAdd" NUMERIC(5,2),
 "AdditionalAdditivesType" CHAR(30),
 "AdditionalAdditivesPerToAdd" NUMERIC(5,2),
 "BalanceCaproPerToAdd" NUMERIC(5,2) );