CREATE TABLE "GCG_6495_RECIPE_CHG" (
 "RequestID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RequestID" UNIQUE USING 0,
 "UpdateDate" DATE,
 "RecipeTable" CHAR(25),
 "Grade" CHAR(4),
 "Size" CHAR(16),
 "ActivatorPerToAdd" NUMERIC(5,2),
 "ActivatorType" CHAR(30),
 "CatalystPerToAdd" NUMERIC(5,2),
 "PourTemp" NUMERIC(5,0),
 "PourWeight" NUMERIC(5,0),
 "DyeType" CHAR(30),
 "DyePerToAdd" NUMERIC(5,2),
 "AdditionalType" CHAR(30),
 "AdditionalPerToAdd" NUMERIC(5,2),
 "AdditionalAdditivesType" CHAR(30),
 "AdditionalAdditivesPerToAdd" NUMERIC(5,2),
 "BalanceCaproPerToAdd" NUMERIC(5,2),
 "Reason1" BIT NOT NULL,
 "Reason2" BIT NOT NULL,
 "Reason3" BIT NOT NULL,
 "Reason4" BIT NOT NULL,
 "Reason5" BIT NOT NULL,
 "Reason6" BIT NOT NULL,
 "Reason7" BIT NOT NULL,
 "Reason8" BIT NOT NULL,
 "Reason9" BIT NOT NULL,
 "Reason10" BIT NOT NULL,
 "Reason11" BIT NOT NULL,
 "Reason12" BIT NOT NULL,
 "Reason13" BIT NOT NULL,
 "Reason14" BIT NOT NULL,
 "Reason15" BIT NOT NULL,
 "Reason16" BIT NOT NULL,
 "Reason17" BIT NOT NULL,
 "Reason18" BIT NOT NULL,
 "Reason19" BIT NOT NULL,
 "Reason20" BIT NOT NULL,
 "Reason21" BIT NOT NULL,
 "Reason22" BIT NOT NULL,
 "Reason23" BIT NOT NULL,
 "Reason24" BIT NOT NULL,
 "Reason25" BIT NOT NULL,
 "Reason26" BIT NOT NULL,
 "Reason27" BIT NOT NULL,
 "Reason28" BIT NOT NULL,
 "Reason29" BIT NOT NULL,
 "Reason30" BIT NOT NULL,
 "Other" BIT NOT NULL,
 "Comments" LONGVARCHAR,
 "Status" char(20),
 "RequestedBy" CHAR(8),
 "RequestedTimeStamp" DATETIME,
 "ProcessedBy" CHAR(8),
 "ProcessedTimeStamp" DATETIME );